### ISSUE TITLE
Error: Package subpath './lib/cli-engine' is not defined by "exports"

### ISSUE THREAD

**Issue by syphernl** [halkeye/eslint-formatter-multiple#74]
Running `eslint` with `--format eslint-formatter-multiple` results in an error:

```
There was a problem loading formatter: /app/node_modules/eslint-formatter-multiple/index.js
Error: Package subpath './lib/cli-engine' is not defined by "exports" in /app/node_modules/eslint/package.json
```

We're using `eslint` version `8.11.0`.

**Comment by halkeye** [comment]
hrmmm

i havn't had a need to use this in a while. I'll take a peek when I can, but would love a PR

**Comment by sumitjawale** [comment]
Any update on this one yet?

**Comment by halkeye** [comment]
from me? no, like i said, I don't use it anymore, so hasn't been a priority.

**Comment by v1v** [comment]
https://github.com/eslint/eslint/issues/15194 seems to be related

**Comment by v1v** [comment]
PR -> https://github.com/halkeye/eslint-formatter-multiple/pull/77

**Comment by halkeye** [comment]
https://github.com/halkeye/eslint-formatter-multiple/releases/tag/v2.0.0
